name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "40 1 * * *"

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings
  CARGO_HOME: ~/.cargo

jobs:
  pre_ci:
    uses: dtolnay/.github/.github/workflows/pre_ci.yml@master

  test:
    name: Rust ${{ matrix.rust }} on ${{ matrix.os }}
    needs: pre_ci
    if: needs.pre_ci.outputs.continue
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [nightly, beta, stable, 1.56.0]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Enable type layout randomization
        if: matrix.rust == 'nightly'
        run: echo RUSTFLAGS=${RUSTFLAGS}\ -Zrandomize-layout >> $GITHUB_ENV
      - run: cargo test

  security:
    name: Security Audit
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
